# Archivio "Versetto del Giorno" — testi di pubblico dominio (Diodati 1885 e
# formulazioni tradizionali). L'amministratore puo' aggiungere/modificare i
# versetti dal pannello; questo elenco serve solo come seed iniziale.
# Campi: text, reference, book, chapter, verse.

VERSES_SEED = [
    {"text": "Poiché Iddio ha tanto amato il mondo, che ha dato il suo unigenito Figliuolo, affinché chiunque crede in lui non perisca, ma abbia vita eterna.", "reference": "Giovanni 3:16", "book": "Giovanni", "chapter": 3, "verse": 16},
    {"text": "Il Signore è il mio pastore, nulla mi mancherà.", "reference": "Salmi 23:1", "book": "Salmi", "chapter": 23, "verse": 1},
    {"text": "Confida nell'Eterno con tutto il tuo cuore, e non t'appoggiare sul tuo discernimento.", "reference": "Proverbi 3:5", "book": "Proverbi", "chapter": 3, "verse": 5},
    {"text": "Io posso ogni cosa in Colui che mi fortifica.", "reference": "Filippesi 4:13", "book": "Filippesi", "chapter": 4, "verse": 13},
    {"text": "Non temere, perché io sono con te; non ti smarrire, perché io sono il tuo Dio.", "reference": "Isaia 41:10", "book": "Isaia", "chapter": 41, "verse": 10},
    {"text": "Or la fede è certezza di cose che si sperano, dimostrazione di cose che non si vedono.", "reference": "Ebrei 11:1", "book": "Ebrei", "chapter": 11, "verse": 1},
    {"text": "Venite a me, voi tutti che siete travagliati ed aggravati, ed io vi darò riposo.", "reference": "Matteo 11:28", "book": "Matteo", "chapter": 11, "verse": 28},
    {"text": "L'Eterno combatterà per voi, e voi ve ne starete tranquilli.", "reference": "Esodo 14:14", "book": "Esodo", "chapter": 14, "verse": 14},
    {"text": "Getta sull'Eterno il tuo peso, ed egli ti sosterrà.", "reference": "Salmi 55:22", "book": "Salmi", "chapter": 55, "verse": 22},
    {"text": "Ogni cosa coopera al bene di quelli che amano Dio.", "reference": "Romani 8:28", "book": "Romani", "chapter": 8, "verse": 28},
    {"text": "Cerca prima il regno di Dio e la sua giustizia, e tutte queste cose vi saranno sopraggiunte.", "reference": "Matteo 6:33", "book": "Matteo", "chapter": 6, "verse": 33},
    {"text": "La tua parola è una lampada al mio piede, ed una luce al mio sentiero.", "reference": "Salmi 119:105", "book": "Salmi", "chapter": 119, "verse": 105},
    {"text": "Sii forte e coraggioso; non temere e non ti spaventare, perché l'Eterno, il tuo Dio, sarà con te dovunque andrai.", "reference": "Giosuè 1:9", "book": "Giosuè", "chapter": 1, "verse": 9},
    {"text": "Se Dio è per noi, chi sarà contro di noi?", "reference": "Romani 8:31", "book": "Romani", "chapter": 8, "verse": 31},
    {"text": "Io sono la via, la verità e la vita; nessuno viene al Padre se non per mezzo di me.", "reference": "Giovanni 14:6", "book": "Giovanni", "chapter": 14, "verse": 6},
    {"text": "Rallegratevi sempre nel Signore; da capo dico: rallegratevi.", "reference": "Filippesi 4:4", "book": "Filippesi", "chapter": 4, "verse": 4},
    {"text": "Non angustiatevi di nulla; ma in ogni cosa siano le vostre richieste rese note a Dio in preghiera e supplicazione con ringraziamento.", "reference": "Filippesi 4:6", "book": "Filippesi", "chapter": 4, "verse": 6},
    {"text": "E la pace di Dio, che sopravanza ogni intelligenza, guarderà i vostri cuori e i vostri pensieri in Cristo Gesù.", "reference": "Filippesi 4:7", "book": "Filippesi", "chapter": 4, "verse": 7},
    {"text": "L'Eterno è la mia luce e la mia salvezza; di chi temerò?", "reference": "Salmi 27:1", "book": "Salmi", "chapter": 27, "verse": 1},
    {"text": "Quelli che sperano nell'Eterno acquistano nuove forze, si levano a volo come aquile.", "reference": "Isaia 40:31", "book": "Isaia", "chapter": 40, "verse": 31},
    {"text": "Il Signore è vicino a quelli che hanno il cuore rotto, e salva quelli che hanno lo spirito contrito.", "reference": "Salmi 34:18", "book": "Salmi", "chapter": 34, "verse": 18},
    {"text": "Gustate e vedete quanto l'Eterno è buono; beato l'uomo che si rifugia in lui.", "reference": "Salmi 34:8", "book": "Salmi", "chapter": 34, "verse": 8},
    {"text": "Io t'ho amato d'un amore eterno; perciò ti ho attratto con benignità.", "reference": "Geremia 31:3", "book": "Geremia", "chapter": 31, "verse": 3},
    {"text": "Io conosco i pensieri che medito per voi, pensieri di pace e non di male, per darvi un avvenire e una speranza.", "reference": "Geremia 29:11", "book": "Geremia", "chapter": 29, "verse": 11},
    {"text": "Le compassioni dell'Eterno sono nuove ogni mattina; grande è la tua fedeltà.", "reference": "Lamentazioni 3:23", "book": "Lamentazioni", "chapter": 3, "verse": 23},
    {"text": "Questo è il giorno che l'Eterno ha fatto; festeggiamo e rallegriamoci in esso.", "reference": "Salmi 118:24", "book": "Salmi", "chapter": 118, "verse": 24},
    {"text": "Ma quelli che aspettano l'Eterno riacquistano forze.", "reference": "Isaia 40:31", "book": "Isaia", "chapter": 40, "verse": 31},
    {"text": "Il frutto dello Spirito è amore, gioia, pace, pazienza, benignità, bontà, fedeltà.", "reference": "Galati 5:22", "book": "Galati", "chapter": 5, "verse": 22},
    {"text": "Voi siete la luce del mondo; una città posta sopra un monte non può essere nascosta.", "reference": "Matteo 5:14", "book": "Matteo", "chapter": 5, "verse": 14},
    {"text": "Amatevi gli uni gli altri; come io v'ho amati, anche voi amatevi gli uni gli altri.", "reference": "Giovanni 13:34", "book": "Giovanni", "chapter": 13, "verse": 34},
    {"text": "Vegliate, state fermi nella fede, portatevi virilmente, fortificatevi.", "reference": "1 Corinzi 16:13", "book": "1 Corinzi", "chapter": 16, "verse": 13},
    {"text": "L'amore è paziente, è benigno; l'amore non invidia.", "reference": "1 Corinzi 13:4", "book": "1 Corinzi", "chapter": 13, "verse": 4},
    {"text": "Ed ora rimangono queste tre cose: la fede, la speranza, l'amore; ma la più grande di esse è l'amore.", "reference": "1 Corinzi 13:13", "book": "1 Corinzi", "chapter": 13, "verse": 13},
    {"text": "Chiedete e vi sarà dato; cercate e troverete; picchiate e vi sarà aperto.", "reference": "Matteo 7:7", "book": "Matteo", "chapter": 7, "verse": 7},
    {"text": "Se dunque il Figliuolo vi farà liberi, sarete veramente liberi.", "reference": "Giovanni 8:36", "book": "Giovanni", "chapter": 8, "verse": 36},
    {"text": "Io sono la risurrezione e la vita; chi crede in me, anche se muore, vivrà.", "reference": "Giovanni 11:25", "book": "Giovanni", "chapter": 11, "verse": 25},
    {"text": "Ecco, io sto alla porta e picchio; se uno ode la mia voce ed apre la porta, io entrerò da lui.", "reference": "Apocalisse 3:20", "book": "Apocalisse", "chapter": 3, "verse": 20},
    {"text": "Non temere, o piccol gregge, perché al Padre vostro è piaciuto di darvi il regno.", "reference": "Luca 12:32", "book": "Luca", "chapter": 12, "verse": 32},
    {"text": "Beati i puri di cuore, perché essi vedranno Iddio.", "reference": "Matteo 5:8", "book": "Matteo", "chapter": 5, "verse": 8},
    {"text": "Se qualcuno è in Cristo, egli è una nuova creatura; le cose vecchie son passate: ecco, son diventate nuove.", "reference": "2 Corinzi 5:17", "book": "2 Corinzi", "chapter": 5, "verse": 17},
    {"text": "La mia grazia ti basta, perché la mia potenza si dimostra perfetta nella debolezza.", "reference": "2 Corinzi 12:9", "book": "2 Corinzi", "chapter": 12, "verse": 9},
    {"text": "Nulla vi è d'impossibile a Dio.", "reference": "Luca 1:37", "book": "Luca", "chapter": 1, "verse": 37},
    {"text": "L'Eterno ti benedica e ti guardi! L'Eterno faccia risplendere il suo volto su te e ti sia propizio!", "reference": "Numeri 6:24", "book": "Numeri", "chapter": 6, "verse": 24},
    {"text": "Ma Iddio mostra la grandezza del proprio amore per noi, in quanto che, mentre eravamo ancora peccatori, Cristo è morto per noi.", "reference": "Romani 5:8", "book": "Romani", "chapter": 5, "verse": 8},
    {"text": "Poiché il salario del peccato è la morte; ma il dono di Dio è la vita eterna in Cristo Gesù.", "reference": "Romani 6:23", "book": "Romani", "chapter": 6, "verse": 23},
    {"text": "Non v'è dunque ora alcuna condanna per quelli che sono in Cristo Gesù.", "reference": "Romani 8:1", "book": "Romani", "chapter": 8, "verse": 1},
    {"text": "Chiunque avrà invocato il nome del Signore sarà salvato.", "reference": "Romani 10:13", "book": "Romani", "chapter": 10, "verse": 13},
    {"text": "Rendete grazie in ogni cosa, perché tale è la volontà di Dio in Cristo Gesù verso di voi.", "reference": "1 Tessalonicesi 5:18", "book": "1 Tessalonicesi", "chapter": 5, "verse": 18},
    {"text": "Iddio non ci ha dato uno spirito di timidità, ma di forza, d'amore e di correzione.", "reference": "2 Timoteo 1:7", "book": "2 Timoteo", "chapter": 1, "verse": 7},
    {"text": "Gettando su lui ogni vostra sollecitudine, perch'egli ha cura di voi.", "reference": "1 Pietro 5:7", "book": "1 Pietro", "chapter": 5, "verse": 7},
    {"text": "Umiliatevi dunque sotto la potente mano di Dio, affinché egli v'innalzi a suo tempo.", "reference": "1 Pietro 5:6", "book": "1 Pietro", "chapter": 5, "verse": 6},
    {"text": "Se confessiamo i nostri peccati, Egli è fedele e giusto da rimetterci i peccati e purificarci da ogni iniquità.", "reference": "1 Giovanni 1:9", "book": "1 Giovanni", "chapter": 1, "verse": 9},
    {"text": "In questo è l'amore: non che noi abbiamo amato Dio, ma ch'Egli ha amato noi.", "reference": "1 Giovanni 4:10", "book": "1 Giovanni", "chapter": 4, "verse": 10},
    {"text": "Noi amiamo perché Egli ci ha amati per il primo.", "reference": "1 Giovanni 4:19", "book": "1 Giovanni", "chapter": 4, "verse": 19},
    {"text": "L'Eterno è buono; è una fortezza nel giorno della distretta, ed egli conosce quelli che si rifugiano in lui.", "reference": "Nahum 1:7", "book": "Nahum", "chapter": 1, "verse": 7},
    {"text": "Rallegrati grandemente, o figliuola di Sion; ecco, il tuo re viene a te; egli è giusto e vittorioso.", "reference": "Zaccaria 9:9", "book": "Zaccaria", "chapter": 9, "verse": 9},
    {"text": "Io alzo gli occhi ai monti... Donde mi verrà l'aiuto? Il mio aiuto vien dall'Eterno, che ha fatto il cielo e la terra.", "reference": "Salmi 121:1", "book": "Salmi", "chapter": 121, "verse": 1},
    {"text": "L'Eterno ti guarderà da ogni male; egli guarderà l'anima tua.", "reference": "Salmi 121:7", "book": "Salmi", "chapter": 121, "verse": 7},
    {"text": "Dio è per noi un rifugio ed una forza, un aiuto sempre pronto nelle distrette.", "reference": "Salmi 46:1", "book": "Salmi", "chapter": 46, "verse": 1},
    {"text": "Statevene tranquilli, e riconoscete che io sono Dio.", "reference": "Salmi 46:10", "book": "Salmi", "chapter": 46, "verse": 10},
    {"text": "Prendi il tuo diletto nell'Eterno, ed egli ti darà quel che il tuo cuore domanda.", "reference": "Salmi 37:4", "book": "Salmi", "chapter": 37, "verse": 4},
    {"text": "Rimetti la tua sorte nell'Eterno; confida in lui, ed egli opererà.", "reference": "Salmi 37:5", "book": "Salmi", "chapter": 37, "verse": 5},
    {"text": "Il pianto può albergare la sera, ma al mattino viene la gioia.", "reference": "Salmi 30:5", "book": "Salmi", "chapter": 30, "verse": 5},
    {"text": "Crea in me un cuore puro, o Dio, e rinnova dentro di me uno spirito ben saldo.", "reference": "Salmi 51:10", "book": "Salmi", "chapter": 51, "verse": 10},
    {"text": "L'Eterno è la mia rocca, la mia fortezza, il mio liberatore.", "reference": "Salmi 18:2", "book": "Salmi", "chapter": 18, "verse": 2},
    {"text": "Benedici, anima mia, l'Eterno, e non dimenticare alcuno de' suoi benefici.", "reference": "Salmi 103:2", "book": "Salmi", "chapter": 103, "verse": 2},
    {"text": "Come un padre è pietoso verso i suoi figliuoli, così è pietoso l'Eterno verso quelli che lo temono.", "reference": "Salmi 103:13", "book": "Salmi", "chapter": 103, "verse": 13},
    {"text": "Celebrate l'Eterno, perch'egli è buono, perché la sua benignità dura in eterno.", "reference": "Salmi 107:1", "book": "Salmi", "chapter": 107, "verse": 1},
    {"text": "Meglio è rifugiarsi nell'Eterno che confidare nell'uomo.", "reference": "Salmi 118:8", "book": "Salmi", "chapter": 118, "verse": 8},
    {"text": "Ho riposto la tua parola nel mio cuore, per non peccare contro di te.", "reference": "Salmi 119:11", "book": "Salmi", "chapter": 119, "verse": 11},
    {"text": "Insegnami a fare la tua volontà, poiché tu sei il mio Dio.", "reference": "Salmi 143:10", "book": "Salmi", "chapter": 143, "verse": 10},
    {"text": "L'Eterno è vicino a tutti quelli che lo invocano, a tutti quelli che lo invocano in verità.", "reference": "Salmi 145:18", "book": "Salmi", "chapter": 145, "verse": 18},
    {"text": "Il timore dell'Eterno è il principio della scienza.", "reference": "Proverbi 1:7", "book": "Proverbi", "chapter": 1, "verse": 7},
    {"text": "Riconoscilo in tutte le tue vie, ed egli appianerà i tuoi sentieri.", "reference": "Proverbi 3:6", "book": "Proverbi", "chapter": 3, "verse": 6},
    {"text": "Custodisci il tuo cuore più d'ogni altra cosa, poiché da esso procedono le sorgenti della vita.", "reference": "Proverbi 4:23", "book": "Proverbi", "chapter": 4, "verse": 23},
    {"text": "Il nome dell'Eterno è una forte torre; il giusto vi corre, e vi trova un alto rifugio.", "reference": "Proverbi 18:10", "book": "Proverbi", "chapter": 18, "verse": 10},
    {"text": "Molti sono i disegni nel cuore dell'uomo, ma il consiglio dell'Eterno è quello che sussiste.", "reference": "Proverbi 19:21", "book": "Proverbi", "chapter": 19, "verse": 21},
    {"text": "Ogni parola di Dio è affinata col fuoco; egli è uno scudo per quelli che confidano in lui.", "reference": "Proverbi 30:5", "book": "Proverbi", "chapter": 30, "verse": 5},
    {"text": "Cercate l'Eterno mentre lo si può trovare; invocatelo mentre è vicino.", "reference": "Isaia 55:6", "book": "Isaia", "chapter": 55, "verse": 6},
    {"text": "Poiché i miei pensieri non sono i vostri pensieri, né le vostre vie sono le mie vie, dice l'Eterno.", "reference": "Isaia 55:8", "book": "Isaia", "chapter": 55, "verse": 8},
    {"text": "Sorgi, risplendi, poiché la tua luce è giunta, e la gloria dell'Eterno s'è levata su te.", "reference": "Isaia 60:1", "book": "Isaia", "chapter": 60, "verse": 1},
    {"text": "Lo Spirito del Signore, dell'Eterno, è su me, perché l'Eterno m'ha unto per recare una buona novella agli umili.", "reference": "Isaia 61:1", "book": "Isaia", "chapter": 61, "verse": 1},
    {"text": "Invocami, e io ti risponderò, e t'annunzierò cose grandi e impenetrabili, che tu non conosci.", "reference": "Geremia 33:3", "book": "Geremia", "chapter": 33, "verse": 3},
    {"text": "Ecco, io sono con voi tutti i giorni, sino alla fine dell'età presente.", "reference": "Matteo 28:20", "book": "Matteo", "chapter": 28, "verse": 20},
    {"text": "Andate dunque, ammaestrate tutti i popoli, battezzandoli nel nome del Padre, del Figliuolo e dello Spirito Santo.", "reference": "Matteo 28:19", "book": "Matteo", "chapter": 28, "verse": 19},
    {"text": "Beati quelli che sono affamati e assetati della giustizia, perché essi saranno saziati.", "reference": "Matteo 5:6", "book": "Matteo", "chapter": 5, "verse": 6},
    {"text": "Splenda così la vostra luce nel cospetto degli uomini, affinché veggano le vostre buone opere e glorifichino il Padre vostro.", "reference": "Matteo 5:16", "book": "Matteo", "chapter": 5, "verse": 16},
    {"text": "Non si può servire a Dio ed a Mammona.", "reference": "Matteo 6:24", "book": "Matteo", "chapter": 6, "verse": 24},
    {"text": "Or a Colui che può, mediante la potenza che opera in noi, fare infinitamente al di là di quel che domandiamo o pensiamo, a lui sia la gloria.", "reference": "Efesini 3:20", "book": "Efesini", "chapter": 3, "verse": 20},
    {"text": "Poiché per grazia siete stati salvati, mediante la fede; e ciò non vien da voi; è il dono di Dio.", "reference": "Efesini 2:8", "book": "Efesini", "chapter": 2, "verse": 8},
    {"text": "Siate benigni gli uni verso gli altri, misericordiosi, perdonandovi a vicenda, come anche Dio vi ha perdonati in Cristo.", "reference": "Efesini 4:32", "book": "Efesini", "chapter": 4, "verse": 32},
    {"text": "Rivestitevi della completa armatura di Dio, onde possiate star saldi contro le insidie del diavolo.", "reference": "Efesini 6:11", "book": "Efesini", "chapter": 6, "verse": 11},
    {"text": "Colui che ha cominciato in voi un'opera buona, la condurrà a compimento fino al giorno di Cristo Gesù.", "reference": "Filippesi 1:6", "book": "Filippesi", "chapter": 1, "verse": 6},
    {"text": "Per me il vivere è Cristo, e il morire guadagno.", "reference": "Filippesi 1:21", "book": "Filippesi", "chapter": 1, "verse": 21},
    {"text": "Qualunque cosa facciate, in parola o in opera, fate ogni cosa nel nome del Signor Gesù.", "reference": "Colossesi 3:17", "book": "Colossesi", "chapter": 3, "verse": 17},
    {"text": "La parola di Cristo abiti in voi doviziosamente.", "reference": "Colossesi 3:16", "book": "Colossesi", "chapter": 3, "verse": 16},
    {"text": "Fedele è colui che vi chiama, ed egli farà anche questo.", "reference": "1 Tessalonicesi 5:24", "book": "1 Tessalonicesi", "chapter": 5, "verse": 24},
    {"text": "Il Signore è fedele, ed egli vi renderà saldi e vi guarderà dal maligno.", "reference": "2 Tessalonicesi 3:3", "book": "2 Tessalonicesi", "chapter": 3, "verse": 3},
    {"text": "Combatti il buon combattimento della fede, afferra la vita eterna.", "reference": "1 Timoteo 6:12", "book": "1 Timoteo", "chapter": 6, "verse": 12},
    {"text": "Ogni scrittura è ispirata da Dio e utile a insegnare, a riprendere, a correggere.", "reference": "2 Timoteo 3:16", "book": "2 Timoteo", "chapter": 3, "verse": 16},
    {"text": "Accostiamoci dunque con piena fiducia al trono della grazia, affinché otteniamo misericordia e troviamo grazia.", "reference": "Ebrei 4:16", "book": "Ebrei", "chapter": 4, "verse": 16},
    {"text": "Gesù Cristo è lo stesso ieri, oggi e in eterno.", "reference": "Ebrei 13:8", "book": "Ebrei", "chapter": 13, "verse": 8},
    {"text": "Reputate una completa allegrezza, fratelli miei, quando venite a trovarvi in prove svariate.", "reference": "Giacomo 1:2", "book": "Giacomo", "chapter": 1, "verse": 2},
    {"text": "Se alcuno di voi manca di sapienza, la chiegga a Dio che dona a tutti liberalmente.", "reference": "Giacomo 1:5", "book": "Giacomo", "chapter": 1, "verse": 5},
    {"text": "Sottomettetevi dunque a Dio; ma resistete al diavolo, ed egli fuggirà da voi.", "reference": "Giacomo 4:7", "book": "Giacomo", "chapter": 4, "verse": 7},
    {"text": "Avvicinatevi a Dio, ed egli si avvicinerà a voi.", "reference": "Giacomo 4:8", "book": "Giacomo", "chapter": 4, "verse": 8},
    {"text": "Mediante le sue lividure voi siete stati guariti.", "reference": "1 Pietro 2:24", "book": "1 Pietro", "chapter": 2, "verse": 24},
    {"text": "Il Signore non ritarda l'adempimento della sua promessa, ma è paziente verso voi.", "reference": "2 Pietro 3:9", "book": "2 Pietro", "chapter": 3, "verse": 9},
    {"text": "Chi ha il Figliuolo ha la vita; chi non ha il Figliuolo di Dio non ha la vita.", "reference": "1 Giovanni 5:12", "book": "1 Giovanni", "chapter": 5, "verse": 12},
    {"text": "Io sono l'Alfa e l'Omega, il primo e l'ultimo, il principio e la fine.", "reference": "Apocalisse 22:13", "book": "Apocalisse", "chapter": 22, "verse": 13},
    {"text": "Egli asciugherà ogni lagrima dagli occhi loro, e la morte non sarà più.", "reference": "Apocalisse 21:4", "book": "Apocalisse", "chapter": 21, "verse": 4},
    {"text": "In principio Iddio creò i cieli e la terra.", "reference": "Genesi 1:1", "book": "Genesi", "chapter": 1, "verse": 1},
    {"text": "L'Eterno provvederà.", "reference": "Genesi 22:14", "book": "Genesi", "chapter": 22, "verse": 14},
    {"text": "Voi avevate pensato del male contro a me; ma Iddio l'ha pensato in bene.", "reference": "Genesi 50:20", "book": "Genesi", "chapter": 50, "verse": 20},
    {"text": "Ama dunque l'Eterno, il tuo Dio, con tutto il cuore, con tutta l'anima e con tutte le forze.", "reference": "Deuteronomio 6:5", "book": "Deuteronomio", "chapter": 6, "verse": 5},
    {"text": "L'Eterno stesso cammina davanti a te; egli sarà con te, non ti lascerà e non ti abbandonerà.", "reference": "Deuteronomio 31:8", "book": "Deuteronomio", "chapter": 31, "verse": 8},
    {"text": "Diletti, se Dio ci ha così amati, anche noi dobbiamo amarci gli uni gli altri.", "reference": "1 Giovanni 4:11", "book": "1 Giovanni", "chapter": 4, "verse": 11},
    {"text": "Nell'amore non c'è paura; anzi, l'amore perfetto caccia via la paura.", "reference": "1 Giovanni 4:18", "book": "1 Giovanni", "chapter": 4, "verse": 18},
    {"text": "Seguitemi, e io vi farò pescatori di uomini.", "reference": "Matteo 4:19", "book": "Matteo", "chapter": 4, "verse": 19},
    {"text": "La messe è grande, ma pochi sono gli operai; pregate dunque il Signore della messe.", "reference": "Matteo 9:37", "book": "Matteo", "chapter": 9, "verse": 37},
    {"text": "Non voi avete scelto me, ma io ho scelto voi, e vi ho costituiti perché andiate e portiate frutto.", "reference": "Giovanni 15:16", "book": "Giovanni", "chapter": 15, "verse": 16},
    {"text": "Io sono la vite, voi siete i tralci; chi dimora in me, ed io in lui, porta molto frutto.", "reference": "Giovanni 15:5", "book": "Giovanni", "chapter": 15, "verse": 5},
    {"text": "Vi ho detto queste cose, affinché abbiate pace in me. Nel mondo avrete tribolazione; ma fatevi animo, io ho vinto il mondo.", "reference": "Giovanni 16:33", "book": "Giovanni", "chapter": 16, "verse": 33},
    {"text": "Questo vi comando: che vi amiate gli uni gli altri.", "reference": "Giovanni 15:17", "book": "Giovanni", "chapter": 15, "verse": 17},
]
