// Standard topical categories for Bible reading plans (classic set, like the
// popular plan apps). The admin picks one from the list (or types a custom one).
// Categories drive the shelves in the library.
export const PLAN_CATEGORIES: string[] = [
  "Ansia",
  "Paura",
  "Tristezza",
  "Felicità",
  "Stress",
  "Solitudine",
  "Rabbia",
  "Perdono",
  "Speranza",
  "Fede",
  "Amore",
  "Relazioni",
  "Matrimonio",
  "Famiglia",
  "Genitori e Figli",
  "Amicizia",
  "Dipendenze",
  "Guarigione",
  "Salute",
  "Lavoro e Finanze",
  "Gratitudine",
  "Pace",
  "Preghiera",
  "Identità",
  "Perdita e Lutto",
  "Dubbi",
  "Nuovi Credenti",
  "Crescita Spirituale",
  "Attualità",
];
